---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      auth:
        secretRef:
          credentials:
            key: token
            name: bws-access-token
            namespace: external-secrets
      organizationID: 8451c672-1458-42a1-9beb-ac110128c949
      projectID: 14c2be51-f646-4441-b0da-b12f0128daf6

