apiVersion: v1
kind: Secret
metadata:
  name: bws-access-token
  namespace: external-secrets
type: Opaque
data:
  token: ENC[AES256_GCM,data:muSrKJGZ1+PreK7t+AueJm8UGbuSn89X66J8R/qRiMF0kIZRr9M+8U89RuCpi/IpcQIV1YseNMWnaQCI78tKPzady0C7aYJKsr+IebiwA2y/YruDU9AfJ9nW1EPQQXhnIjIf4ayy8jYm0WcaNQEEdLT64A1UA9UZ5aE4ek+movk=,iv:GzWE5vv2J6gbPthq68mvVnYBfcViLkV5yWCKJPLToY4=,tag:9bmMkGLShjCkcsc6OKBBgA==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdmhBQngxZkNrZHpSODZV
        SU8wZ0kwSGtzbW1Wdm1hdUhjN1hEY01iSEI0CnpyeXlIUXQ2YVp5c0dFUFllMTFs
        c0RUcjBRODZ0WE11SEhlSGZKUzZuT2sKLS0tIDJHOGVxdEJySUtTSzVUZnc4dDBG
        a1ZPOGhjMmxXcjFKV1dMRW5FQnh3b1UKLWKcWfhZwRAgeOm7tE0vn6yeXTDyUX6R
        lmS0t0WhxEb6hceTQ903Yk218RShGUC4IP4VV5bNqTqwMXRfgFnyAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T00:40:36Z"
  mac: ENC[AES256_GCM,data:JbURcMgdJ4+zPuL90xZAZkKEueAc684Od4L7E4qU8npfDM04KcZ7tIloaps2jfe4nHOZdbDYjRpwvBQpu3Blv/zpaSsy13R9aG+Rr0Qn+3vL07o57Dtfuv2qt5Y6oCXuOoxWKLLrB/LtS3zk4dil4X14uqyspLNqJQASOc++uq8=,iv:JI2YClPkb3FIWWNcMY95nOH1CdfZnU6jQ1AqFmDPvO8=,tag:q1kUQCc+vCjSJ9fApdHewg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
