apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zDXflkSRDWzWGBVo1EvSUJHAnX1Bkj3u2yLMDQ8b3q9LEJdaGfDeCg==,iv:KVWNHt+Gptn59JX1D0shqBzWwJ4KHGMtcouzIiyb66k=,tag:PB0HUjZ9KmbjGsE4Jur7rg==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMi9FT1YrckdFUEh5SHJ2
        VnR6dzV1ZWFOYmhRKzVHMUZRUzJURWJxb3dnClFHaUFMMDNlWTV5NXNZQTBUQ1hh
        UG4xbUppQzA2SG1PR0d5TWdPR0FvdFEKLS0tIHd5ZUpUYytQUFFrVnRqN0c4VVRy
        LytPMkJFUVBiOHZacTI5blRwWmIvOW8Ke/3vYKhBrc5eERr6cjigOjtAWXvV1uC2
        pwBQSdE6yYFH9tnDBAjwFnsSMceM0t6nrxoXOi4/NhsQuTqxPmP5cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T06:54:28Z"
  mac: ENC[AES256_GCM,data:RnHtxmP36bs4npJWRcb1xuJyP+hRQavloAnCMdVk8G7Lnhny5p4UrILVzTn09mdPu/5bU4HcznCZlZDmnWTcQY0AB0gSy427bWWiEHCBktN91jDVH4SO7KCxs06WS6oqJIWkHjA/1dBU1yDDpky/VGUPcNv7NQWFgUE/bejJhHU=,iv:IdDCDnTLeZZkde5vWpIaraS8isD0J+lCWPBF5MbvNzE=,tag:BKiaRukC0hJ8gL8O0TwTuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
