apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:G3GgryqNW/cAZxSKqvmdR04TWAaGqNpBk/uqmM+NqPE+c8doRFtcqw==,iv:Ni4SEQBsN+d3EC6brabutjKb7ylzgvLyEI42IE44Rmk=,tag:xWx+TKNj77DbJId5G2dCDg==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaHdRUUJrZnRCcS9zeTRC
        T2crc3dzNW1XekoyYk5SYmJKQXFUd2x4R0NnCmpwR25COXEzVWM5d1QvNDFETWVP
        eVNxbWZiU2hFeWhRczB3MkJuK0M3L1UKLS0tIE5nZVMzYWhBbmNQWlN6SEk0VkE4
        Uk1Ba1huNzN2bVVlamVaSU9xUmxZeXcKY/6b9nWPOJfFQFcYaM5kSaKogfTlMfSL
        p3+9jNNijaHu5kVsLgjpaaba9wRh84n3hijDdTpUGnA2SYv71cPtXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:14:42Z"
  mac: ENC[AES256_GCM,data:AVkPvwXW6f5YQr448Np7cVqkofeWdJa8nc9tzXjqs6buBNy5ZKpReJcfm5yFQDTb0k+ld1EFCNcLqGKgbfD/M4fFz+k+Jk85OSYHjkFuZtBt/uZpm+7RAioC4LQSEpsaGuuc1jdPcU7r7oVH9RaLL7aX1WSa/YAgfhQ7bjSIKic=,iv:zK6+Vfrc/zaGIj/emJq5Nl7hqwMBXfiDc4hQKoV5+9U=,tag:6Oz/S7QQArANHgHeoULEeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
