apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ewgvx4BqOsFsRWLcaKlLS0D+OmYSSNzJCjrIXlWoDPxtclAbLTylJQ==,iv:cOHDqEAXccBvTl0DtwjXdbG+cKm/W0ECcOBRTjgynnU=,tag:BN5+RrSaqMZ+pGnn4DDTuQ==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMi9FT1YrckdFUEh5SHJ2
        VnR6dzV1ZWFOYmhRKzVHMUZRUzJURWJxb3dnClFHaUFMMDNlWTV5NXNZQTBUQ1hh
        UG4xbUppQzA2SG1PR0d5TWdPR0FvdFEKLS0tIHd5ZUpUYytQUFFrVnRqN0c4VVRy
        LytPMkJFUVBiOHZacTI5blRwWmIvOW8Ke/3vYKhBrc5eERr6cjigOjtAWXvV1uC2
        pwBQSdE6yYFH9tnDBAjwFnsSMceM0t6nrxoXOi4/NhsQuTqxPmP5cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:57:52Z"
  mac: ENC[AES256_GCM,data:I+ly9x1c5S+zenhcJdxVkg1ABL/goUtSaFNPz/UIH9JdsgN3s7oYFw/1taHAWyd+K9TkodEPg/5rcEWzVDxjVv0bFyQXKbCiDIfzrw5cEI7nCAWThGjr93qhBfXK591/HTE07XSVjz1VWz1nhZ/rGnI9hRmSA/9OL/vKnnqBvLk=,iv:8YUtNNCOviw60CP3XYq6/lGvBhbTdxZ34CXTwLsiLcg=,tag:qUvqsceFHcyTF+v6Vl2/rQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
