apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  TZ: ENC[AES256_GCM,data:6JW329AzyRK3chA9/bWO7A==,iv:Dw+urHH32MpI6ot3srjMM81Xxjmj1fEUV+uucol9gNk=,tag:b7eDWz2aittFAbCSHyEcpQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:+u4qwXdZ3K8=,iv:BGDcLO5q7T/diNEG2QI492CWaqCYCAXwMJlH2NqnH4U=,tag:Vmi+H6na/GuQCR1BxvyiBg==,type:str]
  SECRET_OG_DOMAIN: ENC[AES256_GCM,data:6gzfZGBqOQ==,iv:SWlBNVWIUl7nyj4LhxwjpemcAatwsCitY7uMovgwGZE=,tag:yEckuUloh0MbxGF/n/ZD8w==,type:str]
  SECRET_DNS_SERVER: ENC[AES256_GCM,data:eALrNUwgLP0p1A==,iv:jNoaFYfO2WVuDolCBEN+FNK5czxuMVKmqoAwLUJ3dyw=,tag:R0hp+ob5dIANA1eBIy4s6Q==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:fhqfCOSSM4/395o1,iv:bkXeNwehAQANVmknfSUJno+jeTQjnlroN9zKv/Re6ls=,tag:M3lK8aEEzHgw57jL7tCZ5A==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzczEwVFpFT05hNWJxNUhx
        RFErUkNScktRV2UzbGpielFCSnJzV2prUlJrCmdMS1M2dEJGN0JFS2JrbWdzL3Ju
        c2FIWko3SXgxUFdsRjZwdTUrZHBjcVUKLS0tIFg1OGJleTRjaGxhQTIyYlhXOVUw
        VW1IWm14a2xXUUJZcmFNVncyRWxTeFUKE4F4SB6Fwv/lLf+CqAjXrVDmDb1OGtfb
        AYn+Zwazb6OPsXde+CqK+lXdAGroibJHjjZw8UNPQ3/SC4EStVeiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:36:50Z"
  mac: ENC[AES256_GCM,data:3UtgYe4HgQ49FuOGlytA2svDe46XBDdQ6fYyfQCr5EQoSxJOHxJwyfPFHCCerTe7L81AmjvKjhsKPoaIj/GAE224j0pw3NzSsDFd/OBEYqw9K5I7gtVs2vGylPbKxu9ir+r+L60wrMed0tFTmplR8T1GniwEEgGLfByIX7Kfm98=,iv:6p15TA6Xwt2qbs73vTUwuNkWwLN4K2yT9cJjLH0YQAk=,tag:sOVl80YyhfBMLcHaSihjuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
