apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+u4qwXdZ3K8=,iv:BGDcLO5q7T/diNEG2QI492CWaqCYCAXwMJlH2NqnH4U=,tag:Vmi+H6na/GuQCR1BxvyiBg==,type:str]
  SECRET_DNS_SERVER: ENC[AES256_GCM,data:eALrNUwgLP0p1A==,iv:jNoaFYfO2WVuDolCBEN+FNK5czxuMVKmqoAwLUJ3dyw=,tag:R0hp+ob5dIANA1eBIy4s6Q==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzczEwVFpFT05hNWJxNUhx
        RFErUkNScktRV2UzbGpielFCSnJzV2prUlJrCmdMS1M2dEJGN0JFS2JrbWdzL3Ju
        c2FIWko3SXgxUFdsRjZwdTUrZHBjcVUKLS0tIFg1OGJleTRjaGxhQTIyYlhXOVUw
        VW1IWm14a2xXUUJZcmFNVncyRWxTeFUKE4F4SB6Fwv/lLf+CqAjXrVDmDb1OGtfb
        AYn+Zwazb6OPsXde+CqK+lXdAGroibJHjjZw8UNPQ3/SC4EStVeiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T05:57:25Z"
  mac: ENC[AES256_GCM,data:qCvt+vsKmroikK55pVsBPsJN41e68R7vSK9ybOgkRsEY0Gdk0VeCwwSgThRmPGB5UwO+7WdEqPS/y6L55EeJ1LugVu8zKRY3RnSazIKxqVkxbgq8RBVEXLGWAAbSp8o0dxh9AKGfZG1T26KLeHzL9AiwX34AXcHoh4AFrwIoaTc=,iv:qqdg71x2BVzJNdxhg65DqObAZvPBz7V+A5+UaFkhwFo=,tag:70kQHMRfLmjEc85BH6CP3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
