apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+u4qwXdZ3K8=,iv:BGDcLO5q7T/diNEG2QI492CWaqCYCAXwMJlH2NqnH4U=,tag:Vmi+H6na/GuQCR1BxvyiBg==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzczEwVFpFT05hNWJxNUhx
        RFErUkNScktRV2UzbGpielFCSnJzV2prUlJrCmdMS1M2dEJGN0JFS2JrbWdzL3Ju
        c2FIWko3SXgxUFdsRjZwdTUrZHBjcVUKLS0tIFg1OGJleTRjaGxhQTIyYlhXOVUw
        VW1IWm14a2xXUUJZcmFNVncyRWxTeFUKE4F4SB6Fwv/lLf+CqAjXrVDmDb1OGtfb
        AYn+Zwazb6OPsXde+CqK+lXdAGroibJHjjZw8UNPQ3/SC4EStVeiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:57:52Z"
  mac: ENC[AES256_GCM,data:1n49sPGZMNKR5rPMQXXB0iNRnx01ZxR7pZO5yiA+p9x0nPR1kw1JVSBKByt6qTv/64P77brX2oUILigpSkB2HzEb54v+TG9HIsubQtF0yaM9Z100WMoMsFvmXBlx0aqtXSKey5v4PcdQ9xrRgQR1CIF7dE3XciZ31zxnIUe+jmo=,iv:zQ7XIEJ2szBZGnapLleV5lMuUKdweCWySf0zqGDK9ZM=,tag:UGGzvkl8/bOrLK3hlLfd/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
