apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:AeVIQjRI864=,iv:UzfUWiWoqGejtMAc+Ol83wasRA93AbUjY8zB8IHuALI=,tag:nxiEtemGbpYC8z8vIPgBqQ==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc054V2VjR0J1K3psZC8y
        dG9aT2laM0d5dUw4M29sM0ZxQ0hQeWN0NHh3CkJqbUJ3a0MvaTJwQmlwa1I5cldB
        RzdLT20vWmw1KzQ2VXF2dk5adVNTbWMKLS0tIGhEVjZwZjhpUS94NE52L1dqUTJN
        MkxZLzFoZklmRVZVRFBRRWdxNndOYWMKd2iUZy2/wjxUQWeciDLy2zc9HxIshB0n
        zwcJgWG7RwU1Q2l95WE/ydP6IHJZaWVObPHep0zwwr091PJ4fb9Gaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:14:42Z"
  mac: ENC[AES256_GCM,data:MGyxqhDCbayPJkxXjwv80uCdvl4XWkmobKztmOpO91tsTd9CUWX36yjfXV4RM0xsksXi9+Ybu4u0WpOvrzR5LeHFCRyyQu8cePVLmO6Cd1OZPnwDTQDkaiJF9MoM9XrXoGxmxk6+G6riCRHpWZjS/wdwwoATgigbCk4P+tb1bNE=,iv:nV6Dz/aolWo1ukWIFkR5NSQ6xkqSkG7m4IO4Rjg1oHo=,tag:xceY+1oeUX2ouau689mPEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
