apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5nxJsl7JIwDgwqCyLhrWq6Rj+MJKueteftQCmygvWuU=,iv:RwndvFEVY0DMU1Qo3PH5ZzqlnJp1li5dNDsbTSWRUf8=,tag:nl342WjHmkVafwingpBgSQ==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZmRZMGNQb2N5UUNTdEZG
        UGh6Vnl2WUtWWXhzWkRrdTdpeENTUjk3bXdJCmUxc250MFo1TjV1eGNIZEpvc2dt
        SkkwRnNTVDd1TUdBek0wcWFGMWhZL0EKLS0tIERJV1pGZXhWNUxXRWxucmVBTS9H
        MDJSZG1xU1R5QjFBVGU5OE5WeEZQOE0KpMabMwOUpPze+nNIfFp2Eo+4F1+M2kI6
        lzU5M5NQnfbwM4UKxMNJnYXKMFCsWdAFEd3vGMe6uG2hLhX6ND7ENw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:14:42Z"
  mac: ENC[AES256_GCM,data:1C5IzcvoZUNqddcrqA1TSLFg8yUrKEPdkXSil22270khATaA3/Mxdap0ZYzFr05gWOFP19EB+V6FlBIYrRFhqsJtOj28jCx7p4no+lH7ZZBEu/GZkuHjJK1qigmT3dGMF0Hs7m675C9mipoSUoLjv2REaXo2tX/wkTQsSyiuXIE=,iv:S+wJCBQh9i1tfL2ah8oDHX/bo56DV+fNrjFstPPdBw4=,tag:23KGWoZaVHhbWiD14xwCWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
