apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:eWFXtcloIOX1NDNHnFJDqFf6+ZBIA9XVl2P9bmlcDrw=,iv:bNH7RCSe7PUoetWzrwcJRUW5SCMsSKX6pzMYiGTXVb4=,tag:4fst7qrZNIvBk4vgF7S7gw==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYTdnVEZzc1pkU1FPMXpH
        TVlIRXh0ZWt3ZVVuS2JMY0czc2F4Tm8wNXl3CmxBWTVOeHBFSllHV3J6Q2xFejJK
        a0VYVkN1QUNTajRIUGNQdnAvZzRXNEUKLS0tIEtjeDd6cEU2Ry9kZ0FYSzJKWnV2
        UUdnSFg2OW5GSDZpMklsWGdxRzZvNG8KM1YoiRP/kYZNidMDtTnyYGOUGFtKA8ho
        N7pwkDBr4oE1+iL7xirJB0qZXhWtfHnmPAuCwGan/l1GMUQh9AvJ/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:57:52Z"
  mac: ENC[AES256_GCM,data:HRBkmiyntjrWiZqoYYkUEXxb4o6+26Y1e8NnmskLmWkHJt2SWq67dBfuYKTNNC6bP5uUbx8EfwokC/PeeaWoEimPZCBFgIBZS1cSmEQS1IjZGEpYlxBLXYjnPVWWuBF01tf7ibrGIPeAxpzNA+C+8EBnmOk8ofwPazyk7PbE2DE=,iv:OOpMKLou/eer58MIIeclurDH+ptcK6hyhQR7rTSKRp0=,tag:e2aoDOZXqza714cLyzKleQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
