apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:dYzLrcm3Zk0x6z/JvdbjFdqIHUtWmuZXtaH0aE0CQPkaHZBm2iy6Qabl86elAQhm9HIxok20ilvudyhvOdzbdOkN8neXd70PXeEKFlMxFeHtzU8RPCryDPt3xCD6oNAiEHrEGtNqQaBie9YPwu7t1+BX8U6PQgrVJvJTKOJgixN7cMj1gmHlJd0kmMX3pnRorH5TCmmV5ldqJE9sZSz/S0Hifk3+u4FuX7DGy46R2z8O1xhP,iv:Er7sMZ4TddZYl/0Nt70pBTHE74N9spxmbP/kFBOn5+w=,tag:Zc4mmbVsXXNrdk3nnbwXyA==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMWwrZlZpZEtEYUtYblJk
        R2FJNGpIV2puaXh6TXhOejA0QjdOcUszY0NJCndaK3RKTEZmTHlzUW1YMU5pcGJu
        ZDliK1QrT01uTFdWNFB1RTRTUjZ5RlUKLS0tIGg0d0M2dTdhQWU1U1B4alV6ZENu
        eGl6dHBWazRNR096V2NGSTFUNXRzZmsKICpp7kDlSO/kEQ7dL/v+SwkMrzL5Q6f0
        Zg20c1kAvPDDx3JUjsbM8DsEgfNdBMP76q83IooGq8syrTU6dV7trA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:14:42Z"
  mac: ENC[AES256_GCM,data:My5EPfKJTpfxDR4qa7XemcW5bXVNuuABkn2ItjcTAkh4fntk1paCyV3wdwuqXaIyJnroSY6ZmZiYLCWimKPxKl+mvS981ztRSgBWeThKKx3kwamRgkJ4sFjHrAB3RExeytYxQ4/FwI9DTFKh/gk1w85Hdw4Po+cm79oHXwyro0A=,iv:8CZUDufqAxULykCEwtpp7xMazpmWI+CQO+sPuhfSe9U=,tag:jko9YNLXlqyL27d7xLw6Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
