apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:isl3umwFW4OKbYe9mPFTfF0I8QeVbRTn3NqufA0zteaNPJYBfgP5sTRgCEOOymaUfcw2FQfFCSM5sVTJWR0HBL2Z+MnkwF4CmLs2JYKn8M7v56quXsL1GFWDUAfi09hOh1mSR6vnZvoF3/c0/nTy4lzyDkMIwvy+N0SJOivH2iSY0fsVaHSvtvCw0YoJ2UAIuemRY8ZQcH8jfDRe0RtvbRBrGDDuy4dZAmRgkIrqMj0IoVte,iv:1/SbVI/JxHFjit1eqO08ju6S4PHjSrghLUf4tOAbL6c=,tag:RMGOaOxYujb+q6Ilm+KZ0w==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudTNZcjF5YytlaUtzdU1J
        bWRUdjdEcmdWUU1pMW83Lys4S0txWUIxK1RRCmpiU28vdVBtaHVYblRJNUZjMUVo
        RTZjK3JDVjE2ZG41cXNDNytkaWVrVGsKLS0tIDZzWjhkWXpwbnNmZVdSRGo4ZVpa
        OTVFajJwdXBucStCbXhhVVFza2FBOUkK43HAAIulwpjR6FxHehdcDOV0ndNTjIgV
        6LNYJg24HOz25N6m+DrV7T/mgSUPFsFwISnWxg5NKUVIN7VU/zDhqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:57:52Z"
  mac: ENC[AES256_GCM,data:j4zgKoiHB6ewD72pAPpLTAkt0jyzyAE6bd5uwpozfsY+rqFz8m7/IPV34N1DK5HHdMKghYgRum9XJbbK2mcuQLeqYNQ8WAa8CqysGLFcbQqykbiCPU66pTFh0DF8usstcW7sqv80D8KjipHIPzqkGxaTg+P0Zpkz1vU6h9gZXyM=,iv:GnjsDLOmbrx5FvPXPrn0PbJJ2UZYQOdFKysTMWElrww=,tag:dMDsZL0Je8L04CqKsEb3Fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
