apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BY3jfTAPwr0ZCDKF7YLzd03H506ergg9yKMUYR2anT02C6CqiKqcsw==,iv:Zl9TL3P6TSLsLR3PWZGbznTNUCze8+QEsOJ3ROk2pBk=,tag:b2z1NG4Umi34nnPO/IQSKA==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSXpQVEovL1N4dUFyT1Q4
        WG5KRFQ5L05FTXJubUpOQlZZK082UHJkT1VRClZOdnZDVTBEa3VJVlFiTzBGVzhq
        UHorUmgwMStUNUVXWWtYREIvVmFQME0KLS0tIHJWbkR0ZGZWRElWUG43RS9LZWJk
        K2NWdUpkQ1JCMmQrNTFDOU50RVdWaUkKJDD5s/ffQB+6e9SV1tRcjC9pad8kJeDh
        HaKsLtEHhAV+6yFgwcHPUBZgJyHglVn6y4Gp7I9+6Yuvur0cPJvSGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:14:42Z"
  mac: ENC[AES256_GCM,data:7w3RaKW9XM3Kq7jA7C6ptSQ26881Wa6zJGvUrjRusbTzBGVxHo23AHH93giirmBAfD4qGNKmiEntNLd5j+8CzCmQgpFLvte+loMFi8w69Gz+NcyrEX6Wf8Mwxlxl1OYswkMzMkxqzo04Tbeuv3WGr6sySuyhtOuy1IURhJOnO9E=,iv:9fBDW9pNP1d5VN6I9R6T68aKT9EPKiBhRVdnxWP7fFU=,tag:TgHRGZtyY9IGJBoqLptHEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
