---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./envoy.yaml
  - ./gateway-internal.yaml
  - ./gateway-external.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./podmonitor.yaml
