---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: |-
          {{ .postgres_user }}
        password: |-
          {{ .postgres_pw }}
        minio_s3_access_key: |-
          {{ .minio_user }}
        minio_s3_secret_access_key: |-
          {{ .minio_secret }}
  dataFrom:
    - extract:
        key: postgres-superuser
    - extract:
        key: minio-pgsql
